---
- name: nginx install & start services
  hosts: all
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present

  - name: start nginx
    service:
      name: nginx
      state: started

#   - name: delete nginx
#     apt:
#       name: nginx*
#       state: absent
